force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <description>Stores operational information for each arriving or departing flight, including schedule, operational status, aircraft assignment, gate assignment, and related ground operations.</description>
    <label>Flight</label>
    <nameField>
        <displayFormat>FLT-{00000}</displayFormat>
        <label>Flight Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight__c/fields/Flight_Number__c.field-meta.xml
<CustomField>
    <fullName>Flight_Number__c</fullName>
    <label>Flight Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Arrived</fullName>
            </value>
            <value>
                <fullName>At Gate</fullName>
            </value>
            <value>
                <fullName>Cleaning</fullName>
            </value>
            <value>
                <fullName>Refueling</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Boarding</fullName>
            </value>
            <value>
                <fullName>Ready for Departure</fullName>
            </value>
            <value>
                <fullName>Departed</fullName>
            </value>
            <value>
                <fullName>Delayed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FlightBatchJobTest.cls
@isTest
private class FlightBatchJobTest {

    @isTest
    static void testFlightBatchJob() {

        List<Flight__c> flights = new List<Flight__c>();

        for (Integer i = 1; i <= 5; i++) {

            flights.add(new Flight__c(
                Flight_Number__c = 'AI20' + i,
                Status__c = 'Departed'
            ));
        }

        insert flights;

        Test.startTest();

        Database.executeBatch(new FlightBatchJob(), 5);

        Test.stopTest();

        System.assertEquals(
            5,
            [
                SELECT Count()
                FROM Flight__c
                WHERE Status__c = 'Departed'
            ]
        );
    }
}